// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenElection.Central.Infrastructure;

#nullable disable

namespace OpenElection.Central.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005030921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenElection.Central.Domain.Entities.Booth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoothCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoothState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Booth");
                });

            modelBuilder.Entity("OpenElection.Central.Domain.Entities.VoteLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConstituencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DigitalSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousVoteHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoteHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoterHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoothId");

                    b.ToTable("VoteLedger");
                });
#pragma warning restore 612, 618
        }
    }
}
